os: osx
language: swift
osx_image: xcode12.4

cache:
  bundler: true
  directories:
   - /home/travis/.rvm/

addons:
  homebrew:
    brewfile: true

install:
  - cd src/xcode
  - bundle install --jobs=8
before_script:
  - bundle --version
  - fastlane --version
  - swiftlint version

jobs:
  include:
    - stage: "Tests"
      script: bundle exec fastlane test testplan:UnitTests
      name: "Unit Tests"
    - script: bundle exec fastlane test testplan:UITests
      name: "UI Tests"
    - script: bundle exec fastlane lint
      name: "Lint"

notifications:
  email: false
