os: osx
language: swift
osx_image: xcode12.4

cache: bundler

addons:
  homebrew:
    brewfile: true

before_install:
  - set -euo pipefail
  - bundle --version
  - fastlane --version
  - swiftlint version
install:
  - bundle install --path=vendor --jobs=8
script:
  - fastlane lint
  - fastlane test
