os: osx
language: swift
osx_image: xcode12.4

cache: bundler

addons:
  homebrew:
    brewfile: true

before_install:
  - set -e
  - cd src/xcode
install:
  - bundle install --verbose --jobs=8
before_script:
  - bundle --version
  - fastlane --version
  - swiftlint version
script:
  - fastlane lint
  - fastlane test
