os: osx
language: swift
osx_image: xcode12.4

cache: bundler

addons:
  homebrew:
    brewfile: true

before_install:
  - pwd
  - ls -la
install:
  - cd src/xcode
  - bundle install --jobs=8
before_script:
  - bundle --version
  - fastlane --version
  - swiftlint version

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: bundle exec fastlane test testplan:UnitTests

    - script: bundle exec fastlane test testplan:UITests
      name: "UI Tests"
      
    - stage: lint
      script:
        - fastlane lint
