os: osx
language: swift
osx_image: xcode12.4

cache: bundler

addons:
  homebrew:
    brewfile: true

before_install:
  - cd src/xcode
install:
  - bundle install --path=vendor --jobs=8
script:
  - fastlane test
